spring:
  application:
    name: my-restful-service
  message:
    basename: messages
#  security:
#    user:
#      name: user
#      password: password

server:
  port: 8000

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"