spring:
  application:
    name: my-restful-service
  message:
    basename: messages

server:
  port: 8000

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"